GET http://localhost:3000/api/scorelist

###

GET http://localhost:3000/api/scorelist/Player2

###

POST http://localhost:3000/api/scorelist
Content-Type: application/json

{
    "player":"Player5", 
    "score": 1, 
    "bio":"Test Bio"
}
###
PUT http://localhost:3000/api/scorelist/Player12
Content-Type: application/json

{
    "score":2  
}
###

GET http://localhost:3000/api/board

###
POST http://localhost:3000/api/board/new
Content-Type: application/json

{
    "1": "",
    "2": "",
    "3": "",
    "4": "",
    "5": "",
    "6": "",
    "7": "",
    "8": "",
    "9": ""
}
###